name: EntityMetadataPlugin
version: ${version}
main: fr.il_totore.entitymetadata.plugin.Main
authors: [Il_totore]
description: An example of EntityMetadataAPI usages
website: https://github.com/Iltotore/EntityMetadataAPI
commands:
  datawatcher:
    description: Edit datawatcher of all entities of a type.
  parrot:
    description: Set the nearest parrot on the player's shoulder
  nbt:
    description: Set a NBT Tag to the player
  read:
    description: Read a NBT file.
  write:
    description: Write a NBT file